env:
  browser: true
  commonjs: true
  es6: true
  jquery: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  Plotly: true
  moment: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  space-before-function-paren: ["error", {"anonymous": "always", "named": "never", "asyncArrow": "always"}]
  object-curly-spacing: ["error", "never"]
