---

name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '9 0 * * 1'

permissions:
  contents: read

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up Python 3.14
        uses: actions/setup-python@v7
        with:
          python-version: 3.14
      - name: Install dependencies
        run: python -m pip install --upgrade pip tox
      - name: Run tox
        run: tox -e flake8 --skip-missing-interpreters false
  codespell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up Python 3.14
        uses: actions/setup-python@v7
        with:
          python-version: 3.14
      - name: Install dependencies
        run: python -m pip install --upgrade pip tox
      - name: Run tox
        run: tox -e codespell --skip-missing-interpreters false
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up Python 3.14
        uses: actions/setup-python@v7
        with:
          python-version: 3.14
      - name: Install dependencies
        run: python -m pip install --upgrade pip tox
      - name: Run tox
        run: tox -e eslint --skip-missing-interpreters false
